name: Backup current configuration

on:
    workflow_dispatch:
    schedule:
      - cron: '0 20 * * *'

env:
    TENANT_NAME: ${{ secrets.TENANT_NAME }}
    CLIENT_ID: ${{ secrets.CLIENT_ID }}
    CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs: 
    back_up_configuration: 
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Remove existing prod-backup directory
              shell: bash
              run: |
                rm -f -r -v "$GITHUB_WORKSPACE/prod-backup"

            - name: Install IntuneCD
              run: |
                pip3 install IntuneCD

            - name: Run IntuneCD backup
              run: | 
                mkdir -p "$GITHUB_WORKSPACE/prod-backup"
                IntuneCD-startbackup \
                    --mode=1 \
                    --output=json \
                    --path="$GITHUB_WORKSPACE/prod-backup"

            - name: Get date
              shell: bash
              id: get-date
              run: |
                DATEF=`date +%Y.%m.%d`
                echo "::set-output name=date::$DATEF"

            - name: Commit config updates
              uses: stefanzweifel/git-auto-commit-action@v5
              continue-on-error: true
              with:
                commit_message: "Intune config backup ${{steps.get-date.outputs.date}}"
                commit_user_name: ${{ secrets.COMMIT_NAME }}
                commit_user_email: ${{ secrets.COMMIT_EMAIL }}
