name: Backup current configuration

on:
    workflow_dispatch:
    schedule:
      - cron: '0 20 * * *'

env:
    TENANT_NAME: ${{ secrets.TENANT_NAME }}
    CLIENT_ID: ${{ secrets.CLIENT_ID }}
    CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    contents: write
    pull-requests: write

jobs: 
    back_up_configuration: 
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
              with:
                ref: ${{ github.head_ref }}

            - name: Remove existing prod-backup directory
              shell: bash
              run: |
                rm -f -r -v "$GITHUB_WORKSPACE/prod-backup"

            - name: Install IntuneCD
              run: |
                pip3 install IntuneCD

            - name: Run IntuneCD backup
              run: | 
                mkdir -p "$GITHUB_WORKSPACE/prod-backup"
                IntuneCD-startbackup \
                    --mode=1 \
                    --output=json \
                    --path="$GITHUB_WORKSPACE/prod-backup"

            - name: Get date
              shell: bash
              id: get-date
              run: |
                DATEF=`date +%Y.%m.%d`
                echo "::set-output name=date::$DATEF"

            - name: Commit config updates
              uses: stefanzweifel/git-auto-commit-action@v5
              id: commit
              continue-on-error: true
              with:
                commit_message: "Intune config backup ${{steps.get-date.outputs.date}}"
                commit_user_name: ${{ secrets.COMMIT_NAME }}
                commit_user_email: ${{ secrets.COMMIT_EMAIL }}
                branch: ${{steps.get-date.outputs.date}}
                create_branch: true

            - name: Commit config updates
              uses: stefanzweifel/git-auto-commit-action@v5
              id: commit-cfg
              continue-on-error: true
              with:
                commit_message: "Intune config backup ${{steps.get-date.outputs.date}}"
                commit_user_name: ${{ secrets.COMMIT_NAME }}
                commit_user_email: ${{ secrets.COMMIT_EMAIL }}
                branch: ${{steps.get-date.outputs.date}}
                create_branch: true

            - name: Generate markdown document
              if: steps.commit.outputs.changes_detected == 'true'
              id: create-doc
              shell: bash
              run: |
                INTRO="Endpoint Manager backup and documentation generated at $GITHUB_REPOSITORY <img align=\"right\" width=\"96\" height=\"96\" src=\"./logo.png\">"
                IntuneCD-startdocumentation \
                    --path="$GITHUB_WORKSPACE/prod-backup" \
                    --outpath="$GITHUB_WORKSPACE/prod-as-built.md" \
                    --tenantname=$TENANT_NAME \
                    --intro="$INTRO"

            - name: Commit config updates
              uses: stefanzweifel/git-auto-commit-action@v5
              id: commit-doc
              continue-on-error: true
              with:
                commit_message: "Intune documentation created ${{steps.get-date.outputs.date}}"
                commit_user_name: ${{ secrets.COMMIT_NAME }}
                commit_user_email: ${{ secrets.COMMIT_EMAIL }}
                branch: ${{steps.get-date.outputs.date}}
                create_branch: true                    

            - name: create pull request
              run: gh pr create -B main -H ${{steps.get-date.outputs.date}} --title '${{steps.get-date.outputs.date}} - Backup of Intune configuration' --body 'Created by Github action'
